# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rand',
            field=models.IntegerField(default=32),
        ),
    ]
