# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_auto_20170611_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='rand',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
