# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_auto_20170611_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rand',
            field=models.IntegerField(default=53),
        ),
    ]
