# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_auto_20170611_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rand',
            field=models.IntegerField(default=63),
        ),
    ]
