# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_auto_20170611_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rand',
            field=models.IntegerField(default=44),
        ),
    ]
